name: Clojure CI

on:
  schedule:
    - cron:  '0 7 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Emacs
      # You may pin to the exact commit or the version.
      # uses: purcell/setup-emacs@8df1449990a2a3c64cd08f028a0f05a193191f49
      uses: purcell/setup-emacs@v2.0
      with:
        version: 27.1
    - uses: actions/checkout@v2
    - name: Tangle Sources
      run: emacs --batch -l tangle.el
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
