name: Clojure CI

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 27.1
        
    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@5.0
      with:
        cli: 1.11.1.1113 # Clojure CLI based on tools.deps
          
    - uses: actions/checkout@v2
    - name: Tangle Sources
      run: emacs --batch -l tangle.el

    - name: Run tests
      run: clojure -T:build test
